# Generated by Django 3.2.12 on 2024-07-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='rating',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin')], default='EMPLOYEE', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
