# Generated by Django 3.2.12 on 2024-07-03 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Appraisal', '0002_auto_20240702_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute1', models.IntegerField(blank=True, null=True)),
                ('attribute2', models.IntegerField(blank=True, null=True)),
                ('attribute3', models.IntegerField(blank=True, null=True)),
                ('attribute4', models.IntegerField(blank=True, null=True)),
                ('attribute5', models.IntegerField(blank=True, null=True)),
                ('attribute6', models.IntegerField(blank=True, null=True)),
                ('attribute7', models.IntegerField(blank=True, null=True)),
                ('attribute8', models.IntegerField(blank=True, null=True)),
                ('attribute9', models.IntegerField(blank=True, null=True)),
                ('attribute10', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='employeeattribute',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='EmployeeAttribute',
        ),
    ]
