# Generated by Django 3.2.12 on 2024-07-04 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisal', '0003_auto_20240703_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appraisal.employee'),
        ),
    ]
