# Generated by Django 5.0.7 on 2024-07-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisal', '0004_alter_attributes_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributes',
            old_name='attribute1',
            new_name='ability_to_plan',
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='attribute10',
            new_name='adaptable',
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='attribute2',
            new_name='communication',
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='attribute3',
            new_name='confidence',
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='attribute4',
            new_name='creativity',
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='attribute5',
            new_name='learning_power',
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='attribute6',
            new_name='passion_to_work',
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='attribute7',
            new_name='problem_solving',
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='attribute8',
            new_name='respect_of_deadlines',
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='attribute9',
            new_name='time_management',
        ),
    ]
