# Generated by Django 5.0.7 on 2024-07-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisal', '0005_rename_attribute1_attributes_ability_to_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
    ]
