# Generated by Django 5.0.6 on 2024-07-17 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisal', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
