# Generated by Django 5.0.6 on 2024-07-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisal', '0009_employee_date_of_birth_employee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_taken',
            field=models.IntegerField(),
        ),
    ]
